### ISSUE TITLE
支持其他数据源吗？

### ISSUE THREAD

**Issue by spjich** [chengdedeng/perseus#1]
支持 dbcp c3p0 druid 这些主流的数据源吗

**Comment by chengdedeng** [comment]
支持多种数据库连接池。我在[DynamicDataSource](https://github.com/chengdedeng/perseus/blob/master/src/main/java/info/yangguo/perseus/DynamicDataSource.java)中加了一个判断，只是为了打印一行日志，并不限定使用何种连接池。

`
 if (returnDataSource instanceof org.apache.tomcat.jdbc.pool.DataSource) {
            org.apache.tomcat.jdbc.pool.DataSource source = (org.apache.tomcat.jdbc.pool.DataSource) returnDataSource;
            String jdbcUrl = source.getUrl();
            log.info("JdbcUrl:{}", jdbcUrl);
        }
`
